name: Sync with RosettaNet

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull_from_upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git environment
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Checkout target repository
        uses: actions/checkout@v3

      - name: Add upstream and pull changes
        run: |
          git remote add upstream https://github.com/Digine-Labs/rosettanet.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories || true

      - name: Skip commit if no changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit, skipping push."
            exit 0
          fi

      - name: Commit and push changes back to target repository
        run: |
          git add .
          git commit -m "Sync with RosettaNet, excluding workflows"
          git push https://x-access-token:${{ secrets.SECOND_REPO_TOKEN }}@github.com/Boreas09/ci-deneme.git main
