name: Push to Multiple Repositories

on:
  push:
    branches:
      - main

jobs:
  sync_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "boreas09"
          git config --global user.email "bora_atik98@hotmail.com"

      - name: Add second remote
        run: |
          git remote add second-origin https://boreas09:${{ secrets.API_TOKEN_GITHUB }}@github.com/Boreas09/ci-deneme.git

      - name: Push to second repository
        run: git push second-origin main --force
